name: Test Report

on:
  workflow_run:
    workflows: ['Continuous Integration & Delivery']
    types:
      - completed

jobs:
  report:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, windows-2022 ]

    runs-on: ${{ matrix.os }}

    permissions:
      actions: read
      checks: write
      contents: read

    steps:
      # https://github.com/dorny/test-reporter/issues/363#issuecomment-2381625959.
      - name: Publish Test Report
        uses: dorny/test-reporter@v1.9.1
        with:
          artifact: ${{ matrix.os }}
          name: report (${{ matrix.os }})
          path: '*.trx'
          reporter: dotnet-trx
